clear all
close all

%% define root path for functions
if ismac
    code_path = 'blah';
elseif ispc
    code_path = 'blah';
end

%% set paths
cd(code_path)
addpath(genpath(fullfile(code_path,'firstlook')))
rmpath(genpath(fullfile(code_path,'firstlook','.svn')))
addpath(genpath(fullfile(code_path,'helper_files')))
rmpath(genpath(fullfile(code_path,'helper_files','.svn')))
rmpath(genpath(fullfile(code_path,'helper_files','DataToolsTower','Volumes')))

%% Analyse data
TowerRunAnalysis(...
    'tower','M5',...
    'from_date',[2015 07 24 18 0 0],...
    'to_date',[2015 07 25 24 0 0],...
    'data_root','C:\blah\MetData\M5Twr',...
    'config_path','C:\blah\MetData\M5Twr',...
    'config_file','M5_config_TDMS.mat',...
    'outage_path','C:\blah\\MetData\M5Twr',...
    'outage_file','M5_outages.mat',...
    'calibration_path','C:\blah\MetData\M5Twr',...
    'calibration_file','M5_calibrations.mat',...
    'log_path','C:\blah\MetData\M5Twr\QCReports',...
    'log_file','M5_log_interactive.txt',...
    'web_path','C:\webserver\MetData\M5Twr',...
    'DO_MOVE',1);

%% create summary plots
TowerPlotSummaryData('from_date',[2015 07 23 0 0 0],...
    'to_date',[2015 07 25 24 0 0],...
    'data_root','C:\blah\MetData\M5Twr',...
    'config_path','C:\blah\MetData\M5Twr',...
    'config_file','M5_config_TDMS.mat',...
    'QCSummaryPathAndFile','C:\webserver\MetData\M5Twr\M5_QCSummary.png',...
    'DataSummaryPathAndFile','C:\webserver\MetData\M5Twr\M5_ChannelDataSummary.png')

%% Test this data
TowerDeleteCorruptData('from_date',[2009 12 01 0 0 0],...
    'to_date',[2009 12 22 24 0 0],...
    'data_root','C:\blah\metData\M5Twr')


%% copy 10 minute data to the web
TowerExportMonthlyData('from_date',[2014 09 01 0 0 0],...
    'to_date',[2014 12 30 24 0 0],...
    'data_location','C:\blah\MetData\M5Twr',...
    'export_path','C:\webserver\MetData\M5Twr')

%% copy 20 Hz data to the web
TowerCopy20HzData('from_date',[2014 09 01 0 0 0],...
    'to_date',[2014 12 30 24 0 0],...
    'data_root','C:\blah\MetData\M5Twr',...
    'output_root','C:\webserver\MetData\M5Twr')
