function SubDisplayTiming(tower,qcd,dt,f_timing,timing_flag)

% function display_channel_status(tower,datastream,qcd,dt,f_status)
%
% show instrument availability

%% CREATE AXES
axtiming = subplot(1,3,1:2,'Parent',f_timing);
axfile = subplot(1,3,3,'Parent',f_timing);

%% axes and labels
title(axtiming,...
    [datestr(qcd.file.starttime) ' ' tower.timezone ': Channel Status'])

%% FILE INFORMATION
% use axfile
xlim(axfile,[0 1])
ylim(axfile,[0 1])
text(0, 0.5,...
    {[datestr(qcd.file.starttime,'dd mmm yyyy HH:MM') ...
    ' ' tower.timezone ];...
    ' ';....
    ['Data file: ' strrep(tower.processing.datafile.name,'_','\_')];...
    ['Processed on: ' datestr(datenum(tower.processing.datevec), 'mmm dd yyyy, HH:MM')];...
    ['Configuration file: ' strrep(tower.processing.configfile.name,'_','\_')];...
    ['Code version: ' num2str(tower.processing.code.version,'%3.3f')...
    ' (' datestr(tower.processing.code.date,'mmm dd yyyy') ')'];...
    ['Host ' tower.processing.hostname]},...
    'HorizontalAlignment','left',...
    'VerticalAlignment','middle',...
    'Parent',axfile)
set(axfile,'Visible','off')
%title(axfile,'File Information')

%% TIMING INFORMATION
% use axtiming
xmids = 0.00:0.005:0.005*ceil(max(diff(dt))/0.005);
n= hist(axtiming,diff(dt),xmids);
bar(axtiming,xmids,n)
for i = 1:numel(xmids)
    if n(i)>0
        text(xmids(i),n(i),...
            [' ' num2str(n(i))],...
            'rotation',90,'Tag','info',...
            'Parent',axtiming)
    end
end

title(axtiming,'Sampling period')
ylim(axtiming,[0 tower.windowsize*1.25])
xlim(axtiming,[min(xmids) max(xmids)+0.005])
xlabel(axtiming,'Period [s]')
ylabel(axtiming,'Count')

if ~isempty(timing_flag)
    text(min(xlim)+0.15*diff(xlim),...
        min(ylim)+0.85*diff(ylim),...
        'TIMING IRREGULAR',...
        'Parent',axtiming)
else
    text(min(xlim)+0.15*diff(xlim),...
        min(ylim)+0.85*diff(ylim),...
        'TIMING OK',...
        'Parent',axtiming)
end

pretty_xyplot(axtiming)