function plot_windrose(mag,dir,magres,dirres,CUTIN,CUTOUT,title)

% get good data
[magpass,iflag,ifail] = flagstopassflagfail(mag.flags);
[dirpass,iflag,ifail] = flagstopassflagfail(dir.flags);

% get coincident data
[tcxy,ui,di] = get_common_times(mag.date(magpass),dir.date(dirpass),1/(24*60));

% plot it
windrose(mag.val(magpass(ui)),...
    dir.val(dirpass(di)),...
    magres, dirres,...
    'threshold',CUTIN,...
    'Legend','on',...
    'style','compass',...
    'magmax',CUTOUT,...
    'title',title,...
    'bgc','w')